# Generated by Django 5.0.3 on 2024-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('breed', models.CharField(max_length=20)),
            ],
        ),
    ]
